### ISSUE TITLE
UnsafeList.Add does not resize the list automatically, unlike Insert

### ISSUE THREAD

**Issue by DrSmugleaf** [genaray/Arch.Extended#12]
There is no call to EnsureCapacity in Add but there is one in Insert. If this is intended it should probably be added to the xmldoc of the method.

This code will crash the process when i = 11:
```csharp
var list = new UnsafeList<int>(10);
for (int i = 0; i < 100; i++)
{
    list.Add(i);
}
```

---

This will not:
```csharp
var list = new UnsafeList<int>(10);
for (int i = 0; i < 100; i++)
{
    list.Insert(i, i);
}
```

**Comment by genaray** [comment]
Thanks! That should be easy to fix tho :) 
As a small work around just call EnsureCapacity before each call ^^

**Comment by genaray** [comment]
Should be fixed now in the latest commit :) 
Gonna publish it soon as a nugget.

**Comment by genaray** [comment]
38395dc350e16e30c474172d2f327be03b816781 fixes this completely.
