### ISSUE TITLE
Why and what are the generic passed into BaseSystem for?

### ISSUE THREAD

**Issue by Shadowblitz16** [genaray/Arch.Extended#13]
BaseSystem takes two generic parameters which seem to be reduntant

In the example W is a World but a why do we need to pass it if the library already knows what a World is?
```
public WindowSystem  : BaseSystem
{
    private QueryDescription queryDescription = new QueryDescription().WithAll<Rect2D<uint>>();
    public WindowSystem(World world) : base(world)
    {
        
    }
}

```

also T is a float in the example which looks like it corresponds to the float X and Y in Velocity and Position but what if I have a component with multiple different types?

```
struct MyComponent
{
  float X;
  float Y;
  bool Success;
}
```

**Comment by genaray** [comment]
Sorry for the late reply, somehow i havent received any notification.
Well, the particular package does not know what a world is. Since there's no package dependency to arch. 
But you are right, this should get fixed.

**Comment by Shadowblitz16** [comment]
ok thankyou very much!
