### ISSUE TITLE
System.SourceGenerator: How the data param is passed to queries in the generated Update method is unexpected

### ISSUE THREAD

**Issue by shayded-exe** [genaray/Arch.Extended#28]
Being that `Update` takes a `data` param, I would expect that that param is passed directly to the generated queries.
Instead, I see that the `Data` property is passed instead.

For example:
```cs
partial class MovementSystem
{
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public override void Update(in float data)
    {
        MoveQuery(World, in Data);
    }
}
```

What I expect:
```cs
partial class MovementSystem
{
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public override void Update(in float data)
    {
        MoveQuery(World, in data);
    }
}
```

I'm not sure why you would want to pass data to update, but instead use the data set by `BeforeUpdate`.
Honestly I think `Data` property shouldn't exist in `BaseSystem`. If someone wants to derive their own base that has a Data property they can easily do so, but I think it's just unnecessary to complicate the workings of `BaseSystem`.

If the `Data` property is to be kept, I would at least expect `Update` and `AfterUpdate` to also set it.

Regardless, it doesn't make sense for `Data` to be passed for `[Data]` because if the query wanted to use `Data` it could just access it through `this`.

**Comment by genaray** [comment]
Oh thats right, that looks like a leftover from a previous version. Im gonna change that immediately :) Thanks!

**Comment by genaray** [comment]
Is fixed in the next release (and next commit) :)
