### ISSUE TITLE
Source generator does not work as NuGet package in Visual Studio

### ISSUE THREAD

**Issue by SephDB** [genaray/Arch.Extended#3]
When added as a NuGet library to a project in Visual Studio, the source generator gets an error that it can't be loaded because the dll for netstandard2.1 can't be found.

After some googling, it seems only netstandard2.0 source generators are supported by the IDE.
https://github.com/dotnet/roslyn/issues/47087

Is it possible to downgrade to netstandard2.0?

**Comment by Difficulty-in-naming** [comment]
Installing .net standard 2.1 with Visual Studio Installer may solve your problem.
Tested in Rider and Visual Studio 2022, works

**Comment by SephDB** [comment]
I can't find anywhere to "install" .net standard 2.1, and all documentation on source generators in visual studio says only netstandard 2.0 is supported
https://learn.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/source-generators-overview
https://www.thinktecture.com/en/net/roslyn-source-generators-introduction/
That last one has this to say:

> The target framework of the project containing the Source Generator should be set to netstandard2.0, otherwise some IDEs may refuse loading the DLL. For example, JetBrains Rider 2021.3.2 has no issues with netstandard2.1 but Visual Studio 2022 (17.0.4) demands netstandard2.0.

I haven't found anything to suggest that this situation has changed in the current version of VS(17.4.4)

**Comment by Difficulty-in-naming** [comment]
After checking the dependencies, it seems that only .net standard 2.0 is needed. Unity also only supports Roslyn for .net standard 2.0. Maybe we should bring down the API version?

**Comment by genaray** [comment]
Approved, lets bring it down to .NetStandard 2.0 then :)

**Comment by genaray** [comment]
The source generator is now based on .NetStandard2.0, the latest nuget 1.0.7 is currently uploading :) 
Let me know if it now works as expected!

**Comment by SephDB** [comment]
Works perfect now, thanks!
