### ISSUE TITLE
SourceGenerator Tests project is not included in sln file and, apparently tests are failing

### ISSUE THREAD

**Issue by DarKotE** [genaray/Arch.Extended#45]
With something like either `Arch.System.SourceGenerator\Arch.System.SourceGenerator.QueryGenerator\EmptyQueryParameter.DoJob().g.cs(29,45): error CS1579: foreach statement cannot operate on variables of type 'Chunk' because 'Chunk' does not contain a public instance or extension definition for 'GetEnumerator'` or `System.BadImageFormatException : Bad IL format`

**Comment by DarKotE** [comment]
looks like [arch version](https://github.com/genaray/Arch.Extended/blob/bd50e06bb2ebac8232a42e45812d86e0cdb115e2/Arch.System.SourceGenerator.Tests/Arch.System.SourceGenerator.Tests.csproj#L12C1-L12C1) needed to be bumped
but even that OnlyDataParameter test case is still failing for some reason 🤔

**Comment by genaray** [comment]
Should be solved by now
