### ISSUE TITLE
Add support for source generated parallel queries

### ISSUE THREAD

**Issue by SchnozzleCat** [genaray/Arch.Extended#61]
Unless I am missing something, there is currently no way to source generate a query that runs in parallel. This would be a nice enhancement, as otherwise writing parallel queries requires using the more verbose syntax.

**Comment by genaray** [comment]
Its noted here: https://github.com/genaray/Arch/issues/66

**Comment by genaray** [comment]
Solved in #72

**Comment by Jvs34** [comment]
> Solved in #72

@genaray Arch.System hasn't been updated to match the source generator change, could you please publish a new release?
