### ISSUE TITLE
The source generator does not respect nullability being enabled/disabled.

### ISSUE THREAD

**Issue by Epicguru** [genaray/Arch.Extended#69]
As the title states, the source generator always assumes that the Nullable Reference Types feature is enabled and will generate the following line:
`private World? _xx_Initialized;`
![image](https://github.com/genaray/Arch.Extended/assets/26253331/c6ae9baf-21d5-4550-b319-ade73fa415df)

If the user does not have NRT enabled, this causes a warning, and if (like myself) you have warnings as errors enabled, it will make the project unable to compile. Currently the only workaround is to either disable the warning `CS8669` (for the entire project) or enable NRT.

**Comment by genaray** [comment]
Thank you! We should probably fix that :) if you already have a PR, I'd love to take it!

**Comment by Epicguru** [comment]
I will make one today or tomorrow :)

**Comment by LilithSilver** [comment]
Did you manage to make a PR @Epicguru? I'm running into this issue as well. I can take it on if need be.

**Comment by Epicguru** [comment]
I only got round to looking at it this morning, but from my brief research I could not figure out a simple way to determine whether the current generator context has NRT enabled.

 If you already know the solution to this problem, feel free to make a PR, otherwise I will investigate more tomorrow.

**Comment by LilithSilver** [comment]
Is checking the context needed? The source uses `World?` directly, which is only ever valid in a nullable context, so I imagine the solution is just to add the annotations in every case, regardless of whether the user uses them in their code or not.

**Comment by Epicguru** [comment]
Just to be clear, the screenshot of code I posted above is the generated code, not my code.
The generator currently always generates `World?`, see [here in Query.cs](https://github.com/genaray/Arch.Extended/blob/d2c98c0395bb9df7a65f2872ac9b29857c55e88e/Arch.System.SourceGenerator/Query.cs#L263).
The problem is then that the generated code is considered to be part of the project it is generated for, and so will throw warnings if NRT is disabled there, at least that was my experience confirmed by brief testing.

**Comment by Epicguru** [comment]
Actually, reading into the warning message a bit more makes this very simple, I wish I had done that sooner :/

`CS8669 The annotation for nullable reference types should only be used in code within a '#nullable' annotations context. Auto-generated code requires an explicit '#nullable' directive in source.`

It seems that this will be simple to solve then. Either wrap the generated code in `#nullable enable / #nullable restore` or simply get rid of the question mark, since it seems that nullable is considered disabled by default in generated source code.

I will test and make a PR now.
