### ISSUE TITLE
How do I use the EventBus library?

### ISSUE THREAD

**Issue by Atlinx** [genaray/Arch.Extended#9]
EventBus doesn't seem to contain a definition for Send, so I couldn't follow the code sample.

**Comment by Atlinx** [comment]
The issue was due to the event bus source generator not running

**Comment by wiredmatt** [comment]
Hey, how did you solve this?

**Comment by metaphist** [comment]
@wiredmatt https://github.com/genaray/Arch.Extended/issues/23#issuecomment-2099166263

To note: In Unity I was getting an error about Hook not existing when trying to listen directly in a system class. Only static event listener seemed to work.
